#!/usr/bin/env bash
# Write a script that displays "Best School" 10 times using a while loop.
# On the 9th iteration, displays "Hi" before "Best School".

sort=0

while [ $sort -lt 10 ]
do
  if [ $sort -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( sort++ ))
done

